apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-app
  namespace: {{.Values.environment.namespace}}
spec:
  replicas: {{.Values.container.replicas}}
  selector:
    matchLabels:
      app: {{.Release.Name}}-app
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-app
    spec:
      containers:
        - name: {{.Release.Name}}-app
          image: {{.Values.container.image}}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 2
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 5"]
